# Generated by Django 3.0.2 on 2020-01-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla_intereses',
        ),
    ]
