# Generated by Django 3.0.2 on 2020-01-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200120_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Jefa', 'Jefa'), ('Alumno', 'Alumno'), ('Aspirante', 'Aspirante')], max_length=100, null=True),
        ),
    ]
